variables:
  IMAGE: "$MOTO_REGISTRY/$CI_PROJECT_NAME"

stages:
  - build
  - test
  - push

Build PHP 7.2:
  stage: build
  script:
    - docker build --build-arg PHP_VERSION=7.2 --build-arg GITHUB_TOKEN=${GITHUB_MACHINE_TOKEN} --tag $CI_REGISTRY_IMAGE:7.2 --tag ${IMAGE}:7.2 .

Build PHP 7.3:
  stage: build
  script:
    - docker build --build-arg PHP_VERSION=7.3 --build-arg GITHUB_TOKEN=${GITHUB_MACHINE_TOKEN} --tag $CI_REGISTRY_IMAGE:7.3 --tag ${IMAGE}:7.3 .

Build PHP 7.4:
  stage: build
  script:
    - docker build --build-arg PHP_VERSION=7.4 --build-arg GITHUB_TOKEN=${GITHUB_MACHINE_TOKEN} --tag $CI_REGISTRY_IMAGE:7.4 --tag ${IMAGE}:7.4 .

Build PHP 7.4 with SQLServer:
  stage: build
  script:
    - docker build --file Dockerfile-sqlsrv --build-arg PHP_VERSION=7.4 --build-arg GITHUB_TOKEN=${GITHUB_MACHINE_TOKEN} --tag $CI_REGISTRY_IMAGE:7.4-sqlsrv --tag ${IMAGE}:7.4-sqlsrv .

.Test Image: &test
  stage: test
  before_script:
    - docker run --name laravel-${LARAVEL_VERSION}-php${PHP_VERSION} -v composer:/root/.composer/cache --rm --detach ${IMAGE}:${PHP_VERSION} bash -c "rm -rf /var/www && composer create-project laravel/laravel=^${LARAVEL_VERSION} /var/www --prefer-dist --no-dev && chmod -R 777 /var/www/{bootstrap,storage} && /usr/local/bin/start.sh"
    - docker exec laravel-${LARAVEL_VERSION}-php${PHP_VERSION} wait-for-it.sh -t 120 127.0.0.1:80
  script:
    - docker exec laravel-${LARAVEL_VERSION}-php${PHP_VERSION} bash -c "curl -s http://127.0.0.1/ | grep 'Laravel' || exit 1"
  after_script:
    - docker stop laravel-${LARAVEL_VERSION}-php${PHP_VERSION}

Laravel 5 / PHP 7.2:
  <<: *test
  variables:
    LARAVEL_VERSION: "5.1.0"
    PHP_VERSION: "7.2"

Laravel 6 / PHP 7.2:
  <<: *test
  variables:
    LARAVEL_VERSION: "6.1.0"
    PHP_VERSION: "7.2"

Laravel 7 / PHP 7.2:
  <<: *test
  variables:
    LARAVEL_VERSION: "7.1.0"
    PHP_VERSION: "7.2"

Laravel 5 / PHP 7.3:
  <<: *test
  variables:
    LARAVEL_VERSION: "5.1.0"
    PHP_VERSION: "7.3"

Laravel 6 / PHP 7.3:
  <<: *test
  variables:
    LARAVEL_VERSION: "6.1.0"
    PHP_VERSION: "7.3"

Laravel 7 / PHP 7.3:
  <<: *test
  variables:
    LARAVEL_VERSION: "7.1.0"
    PHP_VERSION: "7.3"

Laravel 5 / PHP 7.4:
  <<: *test
  variables:
    LARAVEL_VERSION: "5.1.0"
    PHP_VERSION: "7.4"

Laravel 6 / PHP 7.4:
  <<: *test
  variables:
    LARAVEL_VERSION: "6.1.0"
    PHP_VERSION: "7.4"

Laravel 7 / PHP 7.4:
  <<: *test
  variables:
    LARAVEL_VERSION: "7.1.0"
    PHP_VERSION: "7.4"


Publish Images:
  stage: push
  script:
    - docker push ${IMAGE}:7.2
    - docker push ${CI_REGISTRY_IMAGE}:7.2
    - docker push ${IMAGE}:7.3
    - docker push ${CI_REGISTRY_IMAGE}:7.3
    - docker push ${IMAGE}:7.4
    - docker push ${CI_REGISTRY_IMAGE}:7.4
    - docker push ${IMAGE}:7.4-sqlsrv
    - docker push ${CI_REGISTRY_IMAGE}:7.4-sqlsrv