version: 0.2

env:
  variables:
    IMAGE_NAME: "laravel-docker"
    PHP_VERSION: 7.3
    REGISTRY: "458118949611.dkr.ecr.eu-west-2.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY
  build:
    commands:
      - docker build --tag $REGISTRY/$IMAGE_NAME:$PHP_VERSION prod
      - docker build --tag $REGISTRY/$IMAGE_NAME:$PHP_VERSION-dev dev
  post_build:
    commands:
      - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG-dev
