name: Docker Image CI

on:
  push:

env:
  REGISTRY_IMAGE: ghcr.io/oaklees/laravel-docker

jobs:

  php-7.1:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to docker
      run: |
        docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.DOCKER_LOGIN }}

    - name: Build
      run: |
        docker build --build-arg ALPINE_VERSION=3.7 --tag $REGISTRY_IMAGE:7.1-alpine .

    - name: Push
      run: |
        docker push $REGISTRY_IMAGE:7.1-alpine

  php-7.2:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to docker
        run: |
          docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.DOCKER_LOGIN }}

      - name: Build
        run: |
          docker build --build-arg ALPINE_VERSION=3.9 --tag $REGISTRY_IMAGE:7.2-alpine .

      - name: Push
        run: |
          docker push $REGISTRY_IMAGE:7.2-alpine

  php-7.3:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to docker
        run: |
          docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.DOCKER_LOGIN }}

      - name: Build
        run: |
          docker build --build-arg ALPINE_VERSION=3.11 --tag $REGISTRY_IMAGE:7.3-alpine .

      - name: Push
        run: |
          docker push $REGISTRY_IMAGE:7.3-alpine
