name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY_IMAGE: ghcr.io/oaklees/laravel-docker

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to docker
      run: |
        docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.DOCKER_LOGIN }}

    - name: Pull image for caching
      run: |
        docker pull $REGISTRY_IMAGE:${{ matrix.php }}
        docker pull ubuntu:18.04

    - name: Build
      run: |
        docker build --cache-from=$CACHE_IMAGES --tag $REGISTRY_IMAGE:${{ matrix.php }} --build-arg PHP_VERSION=${{ matrix.php }} .
      env:
        CACHE_IMAGES: ubuntu:18.04,$REGISTRY_IMAGE:${{ matrix.php }}

    - name: Push
      run: |
        docker push $REGISTRY_IMAGE:${{ matrix.php }}
