name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build & Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PHP_VERSION=7.2
        tags: |
          ghcr.io/oaklees/laravel-docker:7.2
