name: Docker Image CI

on:
  push:

env:
  REGISTRY_IMAGE: ghcr.io/oaklees/laravel-docker

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to docker
      run: |
        docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.DOCKER_LOGIN }}

    - name: Build
      run: |
        docker build --tag $REGISTRY_IMAGE:7.3-alpine .

    - name: Push
      run: |
        docker push $REGISTRY_IMAGE:7.3-alpine
